# Generated by Django 5.2.1 on 2025-05-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Género')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('año_lanzamiento', models.PositiveIntegerField(verbose_name='Año de Lanzamiento')),
                ('elenco', models.CharField(help_text='Separado por comas', max_length=500, verbose_name='Elenco')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación (ej: 8.5)')),
                ('portada_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la Portada')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('generos', models.ManyToManyField(to='catalogo.genero', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('año_lanzamiento', models.PositiveIntegerField(verbose_name='Año de Lanzamiento')),
                ('elenco', models.CharField(help_text='Separado por comas', max_length=500, verbose_name='Elenco')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación (ej: 8.5)')),
                ('portada_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la Portada')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('iframe_url', models.URLField(max_length=500, verbose_name='URL del Iframe de Video')),
                ('generos', models.ManyToManyField(to='catalogo.genero', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('año_lanzamiento', models.PositiveIntegerField(verbose_name='Año de Lanzamiento')),
                ('elenco', models.CharField(help_text='Separado por comas', max_length=500, verbose_name='Elenco')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación (ej: 8.5)')),
                ('portada_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la Portada')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('generos', models.ManyToManyField(to='catalogo.genero', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_temporada', models.PositiveIntegerField(verbose_name='Número de Temporada')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título de la Temporada (opcional)')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='catalogo.serie')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['numero_temporada'],
                'unique_together': {('serie', 'numero_temporada')},
            },
        ),
        migrations.CreateModel(
            name='TemporadaAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_temporada', models.PositiveIntegerField(verbose_name='Número de Temporada')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título de la Temporada (opcional)')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas_anime', to='catalogo.anime')),
            ],
            options={
                'verbose_name': 'Temporada de Anime',
                'verbose_name_plural': 'Temporadas de Anime',
                'ordering': ['numero_temporada'],
                'unique_together': {('anime', 'numero_temporada')},
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_episodio', models.PositiveIntegerField(verbose_name='Número de Episodio')),
                ('titulo_episodio', models.CharField(max_length=200, verbose_name='Título del Episodio')),
                ('iframe_url', models.URLField(max_length=500, verbose_name='URL del Iframe de Video')),
                ('sinopsis_episodio', models.TextField(blank=True, null=True, verbose_name='Sinopsis del Episodio (opcional)')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='catalogo.temporada')),
            ],
            options={
                'verbose_name': 'Episodio',
                'verbose_name_plural': 'Episodios',
                'ordering': ['numero_episodio'],
                'unique_together': {('temporada', 'numero_episodio')},
            },
        ),
        migrations.CreateModel(
            name='EpisodioAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_episodio', models.PositiveIntegerField(verbose_name='Número de Episodio')),
                ('titulo_episodio', models.CharField(max_length=200, verbose_name='Título del Episodio')),
                ('iframe_url', models.URLField(max_length=500, verbose_name='URL del Iframe de Video')),
                ('sinopsis_episodio', models.TextField(blank=True, null=True, verbose_name='Sinopsis del Episodio (opcional)')),
                ('temporada_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios_anime', to='catalogo.temporadaanime')),
            ],
            options={
                'verbose_name': 'Episodio de Anime',
                'verbose_name_plural': 'Episodios de Anime',
                'ordering': ['numero_episodio'],
                'unique_together': {('temporada_anime', 'numero_episodio')},
            },
        ),
    ]
