# Generated by Django 5.2.1 on 2025-05-20 15:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 20, 15, 24, 1, 976586, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Subida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodioanime',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 20, 15, 24, 8, 425177, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Subida'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=80, verbose_name='Nombre')),
                ('email_autor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (opcional, no se mostrará)')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
